name: proyek_ambw
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.8
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_storage: ^11.4.8
  image_picker: ^0.8.7+3
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.20
  video_player: ^2.6.1
  file_picker: ^5.2.5
  permission_handler: ^10.3.0
  image_cropper: ^1.4.0
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
